export const ON_BOARDING = 'ON_BOARDING';
export const PERSONAL_INFORMATION = 'PERSONAL_INFORMATION';
export const LOCATION_INFORMATION = 'LOCATION_INFORMATION';
export const CONTACT_INFORMATION = 'CONTACT_INFORMATION';
