export const ON_BOARDING = 'ON_BOARDING';
export const REGISTRATION_GROUP = 'REGISTRATION_GROUP';
export const PERSONAL_INFORMATION = 'PERSONAL_INFORMATION';
export const LOCATION_INFORMATION = 'LOCATION_INFORMATION';
export const CONTACT_INFORMATION = 'CONTACT_INFORMATION';
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';
